# Generated by Django 6.0.2 on 2026-02-20 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('framework', 'Frameworks'), ('database', 'Databases'), ('tool', 'Tools & Platforms'), ('soft', 'Soft Skills'), ('other', 'Other')], default='programming', max_length=50)),
                ('proficiency_level', models.IntegerField(default=50, help_text='Proficiency level from 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('icon', models.CharField(blank=True, help_text='Icon class or name', max_length=50, null=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Show in portfolio')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated technologies', max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_visible', models.BooleanField(default=True, help_text='Show in portfolio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-is_current', '-start_date', 'order'],
            },
        ),
    ]
