# Generated by Django 5.0.4 on 2026-02-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_homecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Main bio/introduction text for the about page', null=True)),
                ('skills_languages', models.TextField(blank=True, help_text='Comma-separated programming languages', null=True)),
                ('skills_frameworks', models.TextField(blank=True, help_text='Comma-separated frameworks', null=True)),
                ('skills_tools', models.TextField(blank=True, help_text='Comma-separated tools and platforms', null=True)),
                ('skills_soft', models.TextField(blank=True, help_text='Comma-separated soft skills', null=True)),
                ('internship_1_company', models.CharField(blank=True, help_text='First internship company name', max_length=200, null=True)),
                ('internship_1_position', models.CharField(blank=True, help_text='First internship position', max_length=200, null=True)),
                ('internship_1_date', models.CharField(blank=True, help_text='First internship date range', max_length=100, null=True)),
                ('internship_1_description', models.TextField(blank=True, help_text='First internship description (one point per line)', null=True)),
                ('internship_1_tech', models.CharField(blank=True, help_text='First internship technologies used', max_length=300, null=True)),
                ('internship_2_company', models.CharField(blank=True, help_text='Second internship company name', max_length=200, null=True)),
                ('internship_2_position', models.CharField(blank=True, help_text='Second internship position', max_length=200, null=True)),
                ('internship_2_date', models.CharField(blank=True, help_text='Second internship date range', max_length=100, null=True)),
                ('internship_2_description', models.TextField(blank=True, help_text='Second internship description (one point per line)', null=True)),
                ('internship_2_tech', models.CharField(blank=True, help_text='Second internship technologies used', max_length=300, null=True)),
                ('certificates', models.TextField(blank=True, help_text='Certificates (one per line in format: Certificate Name | Issuing Organization | Date)', null=True)),
                ('education_1_institution', models.CharField(blank=True, help_text='First education institution', max_length=200, null=True)),
                ('education_1_degree', models.CharField(blank=True, help_text='First education degree', max_length=200, null=True)),
                ('education_1_date', models.CharField(blank=True, help_text='First education date range', max_length=100, null=True)),
                ('education_1_cgpa', models.CharField(blank=True, help_text='First education CGPA/Grade', max_length=50, null=True)),
                ('education_1_location', models.CharField(blank=True, help_text='First education location', max_length=100, null=True)),
                ('education_2_institution', models.CharField(blank=True, help_text='Second education institution', max_length=200, null=True)),
                ('education_2_degree', models.CharField(blank=True, help_text='Second education degree', max_length=200, null=True)),
                ('education_2_date', models.CharField(blank=True, help_text='Second education date range', max_length=100, null=True)),
                ('education_2_cgpa', models.CharField(blank=True, help_text='Second education CGPA/Grade', max_length=50, null=True)),
                ('education_2_location', models.CharField(blank=True, help_text='Second education location', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Make this the active about content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Content',
            },
        ),
    ]
