# Generated by Django 5.0.4 on 2026-02-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_aboutcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateField(blank=True, help_text='Project creation date (day, month, year)', null=True),
        ),
    ]
