# Generated by Django A.B on 2026-03-03 00:00
from django.db import migrations, models


def copy_created_to_start(apps, schema_editor):
    Project = apps.get_model('projects_app', 'Project')
    for proj in Project.objects.all():
        if proj.created and not proj.start_date:
            proj.start_date = proj.created
            proj.save(update_fields=['start_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0006_visitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, help_text='Project start date (day, month, year)'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, help_text='Project end date (day, month, year)'),
        ),
        # keep created field for legacy data, already exists
        migrations.RunPython(copy_created_to_start, migrations.RunPython.noop),
    ]
